use_frameworks!

platform :ios, '10.0'

target 'XKFoldTextView_Example' do
  pod 'XKFoldTextView', :path => '../'

  target 'XKFoldTextView_Tests' do
    inherit! :search_paths
  end
  
  pod 'SnapKit'
  
end
